const $ = (id) => document.getElementById(id);
const money = (n) => new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Math.max(0,n));
function calcEMI(principal, annualRate, years){const months=years*12,r=annualRate/12/100;if(!principal||!months)return 0;if(r===0)return principal/months;return principal*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1);}
function creditBand(score){if(score>=750)return["Excellent","A strong credit range in this educational model."];if(score>=700)return["Good","Generally a healthy range, subject to lender criteria."];if(score>=650)return["Fair","Improvement may help reduce lending risk."];if(score>=600)return["Needs attention","Consider improving repayment history and utilization."];return["Low","A low score can make borrowing more difficult or expensive."];}
function analyze(data){const emi=calcEMI(data.loanAmount,9.5,data.tenure),dti=((data.existingEmi+emi)/data.income)*100;let score=50;score+=Math.min(30,Math.max(0,(data.creditScore-600)/10));score+=data.income>=30000?8:0;score+=data.employment==="Salaried"?8:data.employment==="Business owner"?5:0;score+=data.age>=21&&data.age<=55?5:0;score-=Math.max(0,(dti-40)*.6);score=Math.round(Math.max(0,Math.min(100,score)));const eligible=score>=65&&dti<=50&&data.creditScore>=600&&data.age>=18;const reasons=[];if(data.creditScore>=750)reasons.push("Credit score is in the strong range.");else if(data.creditScore<650)reasons.push("Credit score is a major factor reducing the demo score.");if(dti<=40)reasons.push("Estimated debt-to-income ratio is within the preferred demo range.");else reasons.push("Estimated debt-to-income ratio is relatively high.");if(data.income>=30000)reasons.push("Monthly income meets the prototype's baseline.");else reasons.push("Monthly income is below the prototype's baseline.");if(data.employment==="Salaried")reasons.push("Salaried employment receives a positive weight in this demo.");else reasons.push("Employment type receives a neutral or smaller positive weight in this demo.");return{emi,dti,score,eligible,reasons};}
$("eligibilityForm").addEventListener("submit",(e)=>{e.preventDefault();const data={name:$("name").value.trim(),age:+$("age").value,income:+$("income").value,existingEmi:+$("existingEmi").value||0,creditScore:+$("creditScore").value,employment:$("employment").value,loanAmount:+$("loanAmount").value,tenure:+$("tenure").value};if(!data.employment)return alert("Please select employment type.");if(data.income<=0||data.loanAmount<=0)return alert("Please enter valid positive amounts.");const r=analyze(data);$("eligibilityStatus").textContent=r.eligible?"Estimated Eligible":"Needs Review";$("statusIcon").textContent=r.eligible?"✓":"!";$("statusIcon").style.background=r.eligible?"rgba(55,210,145,.15)":"rgba(255,180,84,.12)";$("statusIcon").style.color=r.eligible?"#52e1a0":"#ffbe69";$("eligibilityScore").textContent=r.score;$("eligibilityMessage").textContent=r.eligible?"The prototype indicates that the entered profile meets the demo thresholds.":"The prototype recommends review or improvement before applying.";$("dtiValue").textContent=r.dti.toFixed(1)+"%";$("eligibilityEmi").textContent=money(r.emi);$("creditBand").textContent=creditBand(data.creditScore)[0];$("reasonList").innerHTML=r.reasons.map(x=>`<li>${x}</li>`).join("");$("heroScore").textContent=r.score;$("heroBar").style.width=r.score+"%";$("heroStatus").textContent=r.eligible?"Estimated eligible under demo rules.":"Needs review under demo rules.";$("emiAmount").value=data.loanAmount;$("emiYears").value=data.tenure;$("creditRange").value=data.creditScore;updateCredit();});
function updateCredit(){const s=+$("creditRange").value;$("creditInputDisplay").textContent=s;const[band,advice]=creditBand(s);$("creditBandLarge").textContent=band;$("creditAdvice").textContent=advice;$("creditScore").value=s;}
$("creditRange").addEventListener("input",updateCredit);
function calculateEmiUI(){const p=+$("emiAmount").value||0,rate=+$("emiRate").value||0,years=+$("emiYears").value||0,emi=calcEMI(p,rate,years),total=emi*years*12,interest=total-p;$("emiOutput").textContent=money(emi);$("principalOutput").textContent=money(p);$("interestOutput").textContent=money(interest);$("totalOutput").textContent=money(total);}
$("calcEmi").addEventListener("click",calculateEmiUI);calculateEmiUI();
function scrollToModule(id){document.querySelectorAll(".module").forEach(m=>m.classList.remove("active-module"));document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));const module=$(id);module.classList.add("active-module");document.querySelector(`.tab[data-target="${id}"]`).classList.add("active");module.scrollIntoView({behavior:"smooth",block:"start");}window.scrollToModule=scrollToModule;
document.querySelectorAll(".tab").forEach(tab=>tab.addEventListener("click",()=>scrollToModule(tab.dataset.target)));
function ask(question){const q=(question||$("aiQuestion").value).trim();if(!q)return;const windowEl=$("chatWindow");windowEl.insertAdjacentHTML("beforeend",`<div class="chat user-msg"><div class="bubble">${escapeHtml(q)}</div></div>`);const answer=generateDemoAnswer(q);setTimeout(()=>{windowEl.insertAdjacentHTML("beforeend",`<div class="chat ai-msg"><div class="avatar">F</div><div><strong>FinSight AI</strong><p>${answer}</p></div></div>`);windowEl.scrollTop=windowEl.scrollHeight;},350);$("aiQuestion").value="";}
function generateDemoAnswer(q){const s=q.toLowerCase();if(s.includes("credit")||s.includes("score"))return"To improve your credit profile, focus on timely repayments, keep credit utilization controlled, avoid unnecessary loan applications, and review your credit report for errors. This prototype gives educational guidance only.";if(s.includes("emi")||s.includes("afford"))return"A practical starting point is to compare the new EMI with your monthly income and existing obligations. A high total debt-to-income ratio can increase repayment pressure. Use the EMI Calculator above to test different amounts and tenures.";if(s.includes("loan")||s.includes("eligib"))return"Loan eligibility depends on lender-specific criteria such as income, employment, credit history, existing obligations and requested amount. The score shown here is a transparent academic demo, not a lender decision.";return"For a safer financial decision, compare the total repayment cost, check your existing obligations, maintain an emergency buffer, and verify the lender's terms before applying.";}
function escapeHtml(str){return str.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
$("askAi").addEventListener("click",()=>ask());$("aiQuestion").addEventListener("keydown",e=>{if(e.key==="Enter")ask()});document.querySelectorAll(".suggestions button").forEach(b=>b.addEventListener("click",()=>ask(b.dataset.q)));
$("themeBtn").addEventListener("click",()=>document.body.classList.toggle("light"));